name: taxispy-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - pims
  - trackpy
  - ipython
  - openpyxl
  - pip
  - pip:
    - scoop
    - deap 

