name: taxispy-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11,<3.12
  - numpy
  - pandas
  - matplotlib
  - ipywidgets
  - pims
  - trackpy
  - ipython
  - openpyxl
  - pip
  - pyzmq
  - jupyter
  - ipykernel
  - notebook
  - ffmpeg
  - pip:
    - scoop
    - deap
